/*
 * Made with all the love in the world
 * by scireum in Remshalden, Germany
 *
 * Copyright by scireum GmbH
 * http://www.scireum.de - info@scireum.de
 */

/*
 * This file was generated by the Gradle 'init' task.
 */

rootProject.name = "parsii"
